### ISSUE TITLE
Could not resolve to a User with the username 오류 이슈

### ISSUE THREAD

**Issue by cxxxtxxyxx** [doongjun/commitmon#47]
![image](https://github.com/user-attachments/assets/4d64cbc4-49b6-494c-bbcd-c68874e096ce)

동료 분 readme에 태그를 추가하였으나, 이미지가 제대로 로드되지 않아, 해당 url을 호출하였더니 다음과 같은 현상이 나타나고 있습니다.

readme에 입력한 태그는 다음과 같습니다.
```html
<a href="https://github.com/doongjun/commitmon">
  <img alt="commitmon" src="https://commitmon.me/adventure?username=NoYeonWoo&theme=desert&userFetchType=all" width="600px" />
</a>
```

감사합니다.

**Comment by doongjun** [comment]
@cxxxtxxyxx 
배포되었습니다.
이슈 감사합니다! :)

**Comment by cxxxtxxyxx** [comment]
빠른 수정 감사드립니다 👍😊
