### ISSUE TITLE
User fetch 주기

### ISSUE THREAD

**Issue by JinuYong** [doongjun/commitmon#49]
팔로우 업데이트 주기가 어떻게 되나요?

userFetchType은 defualt로 설정되어 있는 상태인데

서로 팔로우 되어있는 사용자가 한참이 지나도 뜨지 않아 문의드립니다

**Comment by JinuYong** [comment]
아 1시간인가요!

감사합니다 

잘 나오고있습니다

디지몬 선택할 수 있게 하는 것도 고려하고 있으시다고 들었는데

얼른 업데이트 되었으면 좋겠네요 😃

**Comment by doongjun** [comment]
넵 ㅎㅎ 감사합니다~!
